dist: xenial
language: python
python:
  - "3.7"
before_install:
  - cd bin
  - pip install codecov
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - nosetests
  - pylint --disable=C,W count_elastic_docs.py
  - pylint --disable=C,W delete_elastic_indices.py
  - pylint --disable=C,W get_latest_record.py
  - pylint --disable=C,W,R minute_metrics.py
  - pylint --disable=C,W show_elastic_indices.py
after_success:
  codecov
