language: python
python:
  - "3.6"
before_install:
  - cd bin
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - pylint --disable=C,W count_elastic_docs.py
  - pylint --disable=C,W delete_elastic_indices.py
